/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 13.0.1 -O0 -fPIC) */

(* src = "/home/shore/OneDrive/yosys/sv/test.sv:1.1-11.10" *)
(* top =  1  *)
(* hdlname = "\\top" *)
module top();
  (* src = "/home/shore/OneDrive/yosys/sv/test.sv:5.9-5.10" *)
  wire c;
  assign c = 1'h0;
endmodule
